version: '3.8'
services:
  app:
    build: .
    container_name: hire-smart-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: hiresmart
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      CACHE_DRIVER: redis
      REDIS_HOST: redis
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    container_name: hire-smart-db
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: hiresmart
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: hire-smart-redis

  nginx:
    image: nginx:stable-alpine
    container_name: hire-smart-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  pgdata:
